project:
  type: website
  output-dir: docs
website:
  title: "Medina López et al."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Ongoing_res.qmd
        text: Ongoing research
    right: 
      - icon: twitter
        href: www.twitter.com/melanie_medinal
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



